name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Sanity Test
        run: |
          python - << 'EOF'
          print("Sanity OK")
          EOF

  build_and_scan:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image name
        id: img
        run: |
          IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}"
          echo "IMAGE_LOWER=$IMAGE" >> $GITHUB_ENV
          echo "Using image: $IMAGE"

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_LOWER }}:${{ github.sha }} .
          docker tag ${{ env.IMAGE_LOWER }}:${{ github.sha }} ${{ env.IMAGE_LOWER }}:latest

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_LOWER }}:${{ github.sha }}
          format: 'table'
          exit-code: '0'

  push_image:
    runs-on: ubuntu-latest
    needs: build_and_scan

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image name
        id: img
        run: |
          IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}"
          echo "IMAGE_LOWER=$IMAGE" >> $GITHUB_ENV
          echo "Using image: $IMAGE"

      - name: Push Docker images
        run: |
          docker push ${{ env.IMAGE_LOWER }}:${{ github.sha }}
          docker push ${{ env.IMAGE_LOWER }}:latest
