name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Sanity Test
        run: |
          python - << 'EOF'
          print("Sanity OK")
          EOF

  build_and_scan:
    runs-on: ubuntu-latest
    needs: test
    # expose job output so other jobs can use the image repo name
    outputs:
      image_lower: ${{ steps.set_image.outputs.image_lower }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image repository
        id: set_image
        run: |
         IMAGE_LOWER="ghcr.io/${GITHUB_REPOSITORY,,}"
         echo "IMAGE_LOWER=$IMAGE_LOWER" >> $GITHUB_ENV
         echo "image_lower=$IMAGE_LOWER" >> $GITHUB_OUTPUT
         echo "Using image: $IMAGE_LOWER"



      - name: Build Docker image
        run: |
          docker build -t $IMAGE_LOWER:${GITHUB_SHA} .
          docker tag $IMAGE_LOWER:${GITHUB_SHA} $IMAGE_LOWER:latest
          docker images

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_LOWER }}:${{ github.sha }}


          format: 'table'
          exit-code: '0'

  push_image:
    runs-on: ubuntu-latest
    needs: build_and_scan

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: List local images before push
        run: docker images

      - name: Push Docker images
        run: |
          # read the image name from the previous job's outputs into a shell variable
          IMAGE_LOWER="${{ needs.build_and_scan.outputs.image_lower }}"
          echo "Pushing images for: $IMAGE_LOWER"
          docker push "$IMAGE_LOWER:${GITHUB_SHA}"
          docker push "$IMAGE_LOWER:latest"  

      # - name: Push Docker images
      #   run: |
      #     # use the image name set in previous job output
      #     IMAGE_LOWER="${{ needs.build_and_scan.outputs.image_lower }}"
      #     echo "Pushing images for: $IMAGE_LOWER"
      #     docker push "$IMAGE_LOWER:${GITHUB_SHA}"
      #     docker push "$IMAGE_LOWER:latest"
