name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Sanity Test
        run: |
          python - << 'EOF'
          print("Sanity OK")
          EOF

  build_and_scan:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image repository
        run: echo "IMAGE_LOWER=ghcr.io/$(echo \"$GITHUB_REPOSITORY\" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

# And remove IMAGE_LOWER from the top-level 'env' section.

      - name: Build Docker image
        run: |
          docker build -t ${IMAGE_LOWER}:${{ github.sha }} .
          docker tag ${IMAGE_LOWER}:${{ github.sha }} ${IMAGE_LOWER}:latest
          docker images

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${IMAGE_LOWER}:${{ github.sha }}
          format: 'table'
          exit-code: '0'

  push_image:
    runs-on: ubuntu-latest
    needs: build_and_scan

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: List local images before push
        run: docker images

      - name: Push Docker images
        run: |
          docker push ${IMAGE_LOWER}:${{ github.sha }}
          docker push ${IMAGE_LOWER}:latest
