name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/dummy-branch-app
  IMAGE_NAME_LOWER: ghcr.io/${{ github.repository_owner }}/dummy-branch-app

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python - << 'EOF'
          print("Sanity OK")
          EOF

  build_and_scan:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize image name
        run: |
          lower=$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME_LOWER=$lower" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build -t ${{ env.IMAGE_NAME_LOWER }}:${{ github.sha }} .
          docker tag ${{ env.IMAGE_NAME_LOWER }}:${{ github.sha }} ${{ env.IMAGE_NAME_LOWER }}:latest
          docker images

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME_LOWER }}:${{ github.sha }}
          format: 'table'
          exit-code: '0'

  push_image:
      runs-on: ubuntu-latest
      needs: build_and_scan

      steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push both tags
        run: |
          docker images
          docker push ${{ env.IMAGE_NAME_LOWER }}:${{ github.sha }}
          docker push ${{ env.IMAGE_NAME_LOWER }}:latest
